# permissions for end users to view clusterexecutors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterexecutor-viewer-role
rules:
  - apiGroups:
      - dbschema.microsoft.com
    resources:
      - clusterexecutors
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - dbschema.microsoft.com
    resources:
      - clusterexecutors/status
    verbs:
      - get
