# permissions for end users to edit clusterexecutors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterexecutor-editor-role
rules:
  - apiGroups:
      - dbschema.microsoft.com
    resources:
      - clusterexecutors
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - dbschema.microsoft.com
    resources:
      - clusterexecutors/status
    verbs:
      - get
