# permissions for end users to edit cachingpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cachingpolicy-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: schema-operator
    app.kubernetes.io/part-of: schema-operator
    app.kubernetes.io/managed-by: kustomize
  name: cachingpolicy-editor-role
rules:
- apiGroups:
  - kusto.microsoft.com
  resources:
  - cachingpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kusto.microsoft.com
  resources:
  - cachingpolicies/status
  verbs:
  - get
