package schemaregistryapi

// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

// import (
//     "context"
//     "./azure/schemaregistry"
//     "github.com/Azure/go-autorest/autorest"
// )

//         // SchemaGroupsClientAPI contains the set of methods on the SchemaGroupsClient type.
//         type SchemaGroupsClientAPI interface {
//             List(ctx context.Context) (result schemaregistry.SchemaGroups, err error)
//         }

//         var _ SchemaGroupsClientAPI = (*schemaregistry.SchemaGroupsClient)(nil)
//         // SchemaClientAPI contains the set of methods on the SchemaClient type.
//         type SchemaClientAPI interface {
//             GetByID(ctx context.Context, ID string) (result schemaregistry.ReadCloser, err error)
//             GetVersions(ctx context.Context, groupName string, schemaName string) (result schemaregistry.SchemaVersions, err error)
//             QueryIDByContent(ctx context.Context, groupName string, schemaName string, schemaContent string) (result autorest.Response, err error)
//             Register(ctx context.Context, groupName string, schemaName string, schemaContent string) (result autorest.Response, err error)
//         }

//         var _ SchemaClientAPI = (*schemaregistry.SchemaClient)(nil)
