name: Create new release

on:
  workflow_dispatch:
  # no content, allows manual triggering

  # run when a release is published,
  # which creates a new tag
  push:
    tags:
      - v*

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # required to access tags
          submodules: 'true'

      - name: Build & run devcontainer image
        # this always builds a new image from scratch rather than from the build-devcontainer-image workflow output
        # so that we pick up the latest versions of everything
        # NB: if you update this also update live-validation.yml
        id: devcontainer
        run: |
          docker build --tag devcontainer:latest .devcontainer
          mkdir -p $HOME/.docker # in case it doesn’t exist
          container_id=$(docker create -w /workspace -v $GITHUB_WORKSPACE:/workspace -v /var/run/docker.sock:/var/run/docker.sock devcontainer:latest)
          docker start "$container_id"
          echo "{id}={$container_id}" >> $GITHUB_OUTPUT

      # - name: Run Kustomize
      #   run: |
      #     container_id=${{steps.devcontainer.outputs.id}}
      #     docker exec "$container_id" task controller:gen-helm-manifest

      - name: Build & tag Docker image
        run: |
          container_id=${{steps.devcontainer.outputs.id}}
          docker exec -e DOCKER_PUSH_TARGET "$container_id" task controller:docker-tag-version
        env:
          DOCKER_PUSH_TARGET: ghcr.io/microsoft/azure-schema-operator

      # - name: package helm chart
      #   run: |
      #     container_id=${{steps.devcontainer.outputs.id}}
      #     docker exec "$container_id" task package-helm

      - name: Upload release assets
        uses: svenstaro/upload-release-action@2f88c7710e85b1f8b5f6c3a2fcadaa7f865af713 # this is v2, but pinned
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          file: charts/azure-schema-operator-${{ github.ref_name }}.tgz
          file_glob: true

      - name: Login to registry
        # note that all creds are on host and never passed into devcontainer
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push docker image
        run: docker push --all-tags ghcr.io/microsoft/azure-schema-operator/azureschemaoperator
